markdown: rdiscount
permalink: pretty

# Uncomment if you use it inside rails (ex: bloggy)
#destination: ../../public/help
destination: help/

pygments: true
assets:
  js_compressor:  uglifier
  css_compressor: sass
# Uncomment if you use it inside rails (ex: bloggy)
  #baseurl: /help/assets/
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/assets/stylesheets
    - _vendor/assets/javascripts
    - _vendor/assets/fonts
exclude:
  - Gemfile
  - Gemfile.lock
  - README.rdoc
  - .git
  - .gitignore
languages: ['es']
